web_app/config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  resources :transactions, only: [:create, :update] do
    collection do
      post :sent
      post :confirm
    end
  end
  root 'pages#main'
  resources :contracts

  post ':client_id/assign/:order_item_id' => 'order_items#assign', as: :assing_order_item

  get 'reset' => 'dev#reset'
  get 'reload' => 'dev#reload'
  get 'mobile/:username' => 'mobile#show', as: :show_mobile
  post 'mobile/pay/:id' => 'mobile#pay', as: :pay_mobile

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'status' => 'status#check'
      post 'create_contract' => 'alexa_integration#create_contract'
      post 'split_the_bill' => 'alexa_integration#split_the_bill'
      post 'match_product' => 'alexa_integration#match_product'
      post 'ping_phones' => 'alexa_integration#ping_phones'

      match '*path', to: 'base#routing_error', via: :all
    end
  end

end

web_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web_app/app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :owner, class_name: "User" ,foreign_key: "owner_id"
  belongs_to :client, class_name: "User",foreign_key: "client_id"
  belongs_to :order
  has_many :transactions
  has_many :users, through: :transactions
end

web_app/app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_one :contract
end

web_app/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
end

web_app/app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :contract

  # statusy:
  # FRIEND_FOUND - dodano transakcje (bez widocznego zamówienia)
  # NEW - przypisano OrderItem do transakcji
  # PAYMENT_REQUESTED - wysłana do potwierdzenia
  # PAID - zaplacono

  default_scope { order(id: :asc) }
  scope :only_friend_founds, -> { where(status: 'FRIEND_FOUND') }
end

web_app/app/models/user.rb
class User < ApplicationRecord
  has_many :contracts
  has_many :transactions
end

web_app/app/controllers/api/v1/alexa_integration_controller.rb
module Api
  module V1
    class AlexaIntegrationController < BaseController
      def create_contract
        Contracts::Creator.perform(current_user)
        broadcast!
        render json: { status: :ok }, status: :ok
      end

      def split_the_bill
        contract = Contract.last
        Transactions::Creator.perform(contract)
        broadcast!
        render json: { status: :ok }, status: :ok
      end

      def match_product
        client = User.find_by_name(params[:client])
        order_item = OrderItem.find_by_name(params[:item].capitalize)
        broadcast!
        OrderItemAssigner.perform(client: client, order_item: order_item)
      end

      def ping_phones
        Transaction.update_all(status: "PAYMENT_REQUESTED")
        broadcast!
        render json: { status: :ok }, status: :ok
      end

      private

      def broadcast!
        ActionCable.server.broadcast 'documents', message: 'ok'
      end
    end
  end
end

web_app/app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ApplicationController
      include ActionController::MimeResponds
      protect_from_forgery with: :null_session

      before_action :restrict_access
      skip_before_action :authenticate
      skip_before_action :verify_authenticity_token

      respond_to :json

      def routing_error
        head :bad_request
      end

      private

      def restrict_access
        head :unauthorized unless valid_api_key?(request.env['HTTP_X_API_KEY'])
      end

      def valid_api_key?(api_key)
        api_key.eql?('brobill') # TODO: move to .env gem
      end

      rescue_from ActiveRecord::RecordNotFound do |e|
        render json: { error: e.message }, status: :not_found
      end

      rescue_from ActionController::ParameterMissing do |e|
        render json: { error: e.message }, status: :unprocessable_entity
      end
    end
  end
end

web_app/app/controllers/api/v1/status_controller.rb
module Api
  module V1
    class StatusController < BaseController
      def check
        #curl -H "X-Api-Key: mochila" http://localhost:3000/api/v1/status.json
        render json: { status: :ok }, status: :ok
      end
    end
  end
end

web_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate

  private

  def current_user
    User.find_by_name('Current')
  end

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == 'cola' && password == 'cao'
    end
  end
end

web_app/app/controllers/contracts_controller.rb
class ContractsController < ApplicationController

  respond_to :html, :js
  before_action :set_contract, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to contract_path(100)
  end

  def show
    respond_with @contract
  end

  def edit
    respond_with @contract
  end

  def create
    contract = Contracts::Creator.perform(current_user)
    redirect_to contract_path(contract)
  end

  def update
    @contract.update(contract_params)
    respond_with @contract
  end

  def destroy
    @contract.destroy
    respond_with @contract.destroy
  end

  private

  def set_contract
    @contract = Contract.last
  end

  def contract_params
    params[:contract].permit(:owner_id, :client_id, :status, :total_amount, :paid_amount)
  end
end

web_app/app/controllers/dev_controller.rb
class DevController < ApplicationController
  def reset
    FlowHandler.reset!
    redirect_to contracts_path
  end

  def reload
    @contract = Contract.last
  end
end

web_app/app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  respond_to :html, :js


  def show
    @user = User.find_by_name(params[:username].capitalize)
    @transaction = @user.transactions.where(status: "PAYMENT_REQUESTED").last if @user
    respond_with @transaction
  end

  def pay
    @transaction =Transaction.find(params[:id])
    @transaction.update_attributes(status: "PAID")
    ActionCable.server.broadcast 'documents', message: 'ok'
    redirect_to show_mobile_path(username: @transaction.user.name)
  end
end

web_app/app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  #respond_to :js

  # POST
  def assign
    @client = User.find(params[:client_id])
    @order_item = OrderItem.find(params[:order_item_id])

    OrderItemAssigner.perform(client: @client, order_item: @order_item)
  end
end

web_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end
end

web_app/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  #respond_to :js

  # POST
  def create
    @contract = Contract.last #todo!!!
    ::Transactions::Creator.perform(@contract)
    @transactions = @contract.transactions
  end

  # PATCH
  def update # {id: 4, amount: -20,  status: 'NEW'}
   # ::Transactions::Updater.perform(transaction_params)
  end

  def sent
    Transaction.update_all(status: "PAYMENT_REQUESTED")
    @contract = Contract.last #todo!!!
    @transactions = @contract.transactions
    render :create
  end

  def confirm
    Transaction.update_all(status: "PAID")
    @contract = Contract.last #todo!!!
    @transactions = @contract.transactions
    render :create
  end
end

web_app/app/helpers/application_helper.rb
module ApplicationHelper
end

web_app/app/helpers/contracts_helper.rb
module ContractsHelper
end

web_app/app/views/contracts/elements/_buttons.html.erb
<%= link_to 'Podziel',
  transactions_path, method: :post, remote: true, class: 'x-call-transactions btn btn-success btn-lg' if contract.transactions.empty? %>

<%= link_to 'Zatwierdź', '#', class: 'x-transaction-toggle-all  btn btn-success btn-lg' if contract.transactions.only_friend_founds.any? %>

<%= link_to 'Wyślij płatności', sent_transactions_path, method: :post, remote: true, class: 'btn btn-success btn-lg' if contract.transactions.any? && contract.transactions.all? { |t| t.status == 'NEW' } %>


<%= link_to 'Potwierdź płatności', confirm_transactions_path, method: :post, remote: true, class: 'btn btn-success btn-lg' if contract.transactions.any? && contract.transactions.any? { |t| t.status == 'PAYMENT_REQUESTED' } %>

<!--<%= link_to 'Anuluj', contracts_path, class: 'btn btn-default btn-lg' %>

web_app/app/views/contracts/elements/_details.html.erb
<table class="table">
  <tbody>
    <tr>
      <td class="col-lg-8">
        <h5>Należność dotyczy</h5>
          <p class="cell-content">STOLIK 16</p>
      </td>
      <td>
        <h5>Potwierdzenie</h5>
        <div class="alert alert-custom x-fetching hide" role="alert">Potwierdzam warunek transakcji...</div>
        <div class="alert alert-success x-confirmed" role="alert">
          <strong>BEACON UUID:</strong>
          <p>f7826da6-4fa2-4e98-8024-bc5b71e0893e</p>
          <span class="label label-success">Jesteś w pobliżu</span>
        </div>

      </td>
    </tr>
  </tbody>
</table>

web_app/app/views/contracts/elements/_friends.html.erb
<table class="table table-striped table-bordred">
  <tbody class="x-transaction-containers">
  <%= render partial: "transactions/transaction", collection: contract.transactions %>
  </tbody>
</table>

web_app/app/views/contracts/elements/_header.html.erb
<div class="invoice-v1-header">
  <div class="row">
    <div class="col-md-3">
      <p>Numer</p>
      <p><strong>12/32/2017</strong></p>
    </div>

    <div class="col-md-3">
      <p>Data utworzenia</p>
      <p><strong><%= I18n.l contract.created_at, format: :polish %></strong></p>
    </div>

    <div class="col-md-3">
      <p>Ważność</p>
      <p><strong>10 minut</strong></p>
    </div>

    <div class="col-md-3">
      <p>Status</p>
      <p><strong><%= contract.status %></strong></p>
    </div>
  </div>
</div>

web_app/app/views/contracts/elements/_items.html.erb
<table class="table">
  <tbody>
    <tr>
      <td class="col-lg-8">
        <h5>Szczegóły</h5>
        <ul class="list-group cell-content">
          <% contract.order.order_items.each do |order_item| %>
            <li>
              <span class="pull-right"><%= order_item.amount %> PLN</span>
              <p><%= order_item.name %></p>
            </li>
          <% end -%>
        </ul>
      </td>
      <td>
        <h5>Potwierdzenie</h5>
        <div class="alert alert-custom x-fetching hide" role="alert">Potwierdzam warunek transakcji...</div>
        <div class="alert alert-success x-confirmed" role="alert">
          <strong>MENU_WIOSNA_2017.JSON</strong>
          <p>Plik menu jest aktualny</p>
          <span class="label label-success">Pozycje są zgodne</span>
        </div>
      </td>
    </tr>
  </tbody>
</table>

web_app/app/views/contracts/elements/_main_container.html.erb
<%#= SecureRandom.hex %>

<% if contract.blank? %>
  <div class="text-center">
      <h1>
        Brak<br>
        <small>Na Twoim koncie nie ma jeszcze żadnych konkraktów</small>
      </h1>

    <br><br>
    <%= link_to 'Utwórz nowy kontrakt', contracts_path,
      method: :post, class: 'btn btn-success btn-lg' %>
  </div>
<% elsif contract.transactions.any? && contract.transactions.all? { |t| t.status == 'PAID' } %>
  <%= render partial: 'contracts/elements/sucess', locals: { contract: contract } %>
<% else %>

  <%= render partial: 'contracts/elements/header', locals: { contract: contract } %>

  <div class="responsive-table transaction-details x-table-container">
    <% if contract.transactions.any? %>
        <%= render partial: 'contracts/elements/split', locals: { contract: contract } %>

        <%= render partial: 'contracts/elements/items', locals: { contract: contract } %>

        <%= render partial: 'contracts/elements/friends', locals: { contract: contract } %>
    <% else %>

      <%= render 'contracts/elements/owner' %>

      <%= render 'contracts/elements/details' %>

      <%= render 'contracts/elements/payment_data' %>

      <%= render partial: 'contracts/elements/items', locals: { contract: contract } %>

    <% end %>
  </div>

  <br>

  <div class="pull-right x-buttons">
    <%= render partial: 'contracts/elements/buttons', locals: { contract: contract } %>
  </div>
<% end %>

web_app/app/views/contracts/elements/_owner.html.erb
 <table class="table">
  <tbody>
    <tr>
      <td class="col-md-8">
        <h5>Właściciel</h5>
        <p class="cell-content">BROWAR STU MOSTÓW<br/>ul. Jana Długosza 2</br>51-162 Wrocław</p>
      </td>
      <td class="confirmation-cell">
        <h5>Potwierdzenie</h5>

        <div class="alert alert-custom x-fetching hide" role="alert">Potwierdzam warunek transakcji...</div>

        <div class="alert alert-success x-confirmed" role="alert">
          <strong>GPS: 51.1318158,17.05932</strong></br>
          <strong>MAC: 00:0A:E6:3E:FD:E1</strong></br>
          <span class="label label-success">Jesteś na miejscu</span>
        </div>
      </td>
    </tr>
  </tbody>
</table>

web_app/app/views/contracts/elements/_payment_data.html.erb
<table class="table"> <!-- table-confirmed -->
  <tbody>
    <tr>
      <td class="col-lg-8">
        <h5>Konto do płatności</h5>
          <p class="cell-content">PL951090980568751929917064286869</p>
      </td>
      <td>
        <h5>Potwierdzenie</h5>
        <div class="alert alert-custom x-fetching hide" role="alert">
          Potwierdzam warunek transakcji...
        </div>
        <div class="alert alert-success x-confirmed" role="alert">
          <strong>KONTO BZWBK:</strong>
          <p>Browar Stu Mostów Sp. z o.o.</p>
          <span class="label label-success">Konto zaufane</span>
        </div>
      </td>
    </tr>
  </tbody>
</table>

web_app/app/views/contracts/elements/_split.html.erb
<div class="invoice-v1-header more-spaces">
  <h4>PODZIEL RACHUNEK</h4>

  <div class="row">
    <div class="col-md-6">
      <p>Konto do płatności</p>
      <p><strong>PL951090980568751929917064286869</strong></p>
    </div>

    <div class="col-md-2 x-split-number hide">
      <p>Numer</p>
      <p><strong>12/32/2017</strong></p>
    </div>

    <div class="col-md-2 x-split-create-date hide">
      <p>Data utworzenia</p>
      <p><strong><%= I18n.l contract.created_at, format: :polish %></strong></p>
    </div>

    <div class="col-md-2 x-split-paid-date hide">
      <p>Data załapty</p>
      <p><strong><%= I18n.l contract.updated_at, format: :polish %></strong></p>
    </div>
  </div>
</div>

web_app/app/views/contracts/elements/_sucess.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>Konkrakty</h2>
    <hr>
  </div>
</div>
<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <div class="responsive-table">
        <div class="invoice-v1-header alert alert-success">
          <div class="row">
            <div class="col-md-2">
              <p>Numer</p>
              <p><strong>12/32/2017</strong></p>
            </div>

            <div class="col-md-2">
              <p>Kwota</p>
              <p><strong><%= contract.total_amount %> PLN</strong></p>
            </div>


            <div class="col-md-3">
              <p>Data utworzenia</p>
              <p><strong><%= I18n.l contract.created_at, format: :polish %></strong></p>
            </div>

            <div class="col-md-3">
              <p>Data zakończenia</p>
              <p><strong><%= I18n.l DateTime.now, format: :polish %></strong></p>
            </div>

            <div class="col-md-2">
              <p>Status</p>
              <p><strong><%= 'ZAPŁACONO' %></strong></p>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

web_app/app/views/contracts/index.html.erb
<div class="invoice-v1-header">
  <div class="row">
    <div class="col-md-12">
      <h2>Konkrakty</h2>
      <hr>
    </div>
  </div>
</div>

<% if @contracts.empty? %>
  <div class="text-center">
      <h1>
        Brak<br>
        <small>Na Twoim koncie nie ma jeszcze żadnych konkraktów</small>
      </h1>

    <br><br>
    <%= link_to 'Utwórz nowy kontrakt', contracts_path,
      method: :post, class: 'btn btn-success btn-lg' %>
  </div>

<% else %>
  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <div class="responsive-table">
        <% @contracts.each do |contract| %>
          <%= render partial: 'contracts/elements/header', locals: { contract: contract } %>
          <%= render partial: 'contracts/elements/split', locals: { contract: contract } %>

          <div class='pull-right'>
            <%= link_to "Przejdz do kontraktu", contract, class: 'btn btn-success' %>
          </div>
        <% end -%>
      </div>
    </div>
  </div>
<% end %>

web_app/app/views/contracts/show.html.erb
<div class='x-main-container'>
  <%= render partial: 'contracts/elements/main_container', locals: { contract: Contract.last } %>
</div>

web_app/app/views/dev/reload.js.erb
$('.x-main-container').html('<%= j(render partial: "contracts/elements/main_container", locals: { contract: @contract }) %>');

web_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/elements/head' %>

  <body>
    <div class="container invoice invoice-v1">
      <%= render 'layouts/elements/header' %>
      <div class="panel invoice-v1-content">
        <div class="panel-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

web_app/app/views/layouts/elements/_head.html.erb
<head>
  <title>mochila</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- Mobile support -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap -->
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

web_app/app/views/layouts/elements/_header.html.erb
<div class="header-panel shadow-z-2 belka-top">
  <div class="container-fluid">
    <div class="row">
      <div class="bzwbk-logo">
        <%= image_tag 'bz-wbk-logo.jpg' %>
      </div>
      <div class="links">
        <ul>
          <li>Twoje konto</li>
          <li class="active">Transakcje</li>
          <li>Ustawienia</li>
        </ul>
      </div>
    </div>
  </div>
</div>

web_app/app/views/mobile/show.html.erb
<div class="invoice-v1-header">
  <div class="row">
    <div class="col-md-12">
      <h2>Potwierdzenie zapłaty</h2>
      <hr>
    </div>
  </div>
</div>

<div class="text-center">
  <% if @transaction %>
    <h1>
      You have been invited<br>
      <small>to pay the contract for <%= @transaction.name %>
        from <%= I18n.l @transaction.created_at, format: :polish %></small>
    </h1>

    <br><br>

    <%= link_to 'CONFIRM PAYMENT', pay_mobile_path(id: @transaction.id.to_s),
      method: :post, class: 'btn btn-success btn-lg' %>

  <% else %>
    <h1>
      You have no contracts to pay
    </h1>
  <% end -%>
</div>

web_app/app/views/order_items/assign.js.erb
var container = $('.x-user-id-<%= @client.id %>');

if (container !== undefined) {
  container.find('.x-transaction-name').html('<%= @order_item.name %>');
  container.find('.x-transaction-amount').html('<%= @order_item.amount %> PLN');
  container.find('.x-transaction-link').html('');
}

var container = $('.x-buttons');
container.html('<%= j(render partial: "contracts/elements/buttons", locals: { contract: Contract.last  }) %>');

web_app/app/views/pages/main.html.erb
<h1><%= ENV['APP_NAME'] %> - bankITup "Bank 2030"</h1>

<h2>mochila homepage</h2>

<%= link_to 'Kontrakty', contracts_path %> <br>
<%= link_to 'Reset', reset_path %>

web_app/app/views/transactions/_transaction.html.erb
<tr class="x-transaction x-user-id-<%= transaction.user.id %> <%= 'alert alert-success' if transaction.status == 'PAID'%>">
  <td class="col-lg-1">
    <%= image_tag "avatars/#{[transaction_counter.succ, 3].min}.png", size: '100x100' %>
  </td>
  <td>
    <h4><%= transaction.user.name %></h4>
    <div class="person-labels">
      <span class="label label-success">Znajomy z Facebooka</span>
      <span class="label label-success">W tym samym miejscu</span>
      <span class="label label-success">Współpracownik</span>
    </div>

    <br>
    <p>STATUS: <%= I18n.t(transaction.status, scope: :status) %></p>
  </td>

  <% if transaction.status == 'FRIEND_FOUND'  %>
    <td>
      <div class='x-transaction-link hide'>
      <%= select_tag "assigner_qi", options_for_select(OrderItem.all.map{ |item| [item.name, item.id, { 'data-url' => assing_order_item_path(client_id: transaction.user.id, order_item_id: item.id) }] }), prompt: 'Wybierz produkt', class: 'x-transaction-select' %>
      </div>
      <h4 class="x-transaction-name"></h4>
    </td>
  <% else %>
    <td><h4 class="x-transaction-name"><%= transaction.name %></h4></td>
  <% end %>
  <td>
    <h4 class="x-transaction-amount"><%= transaction.amount %> PLN</h4>
  </td>

</tr>

web_app/app/views/transactions/create.js.erb
$('.x-call-transactions').remove();

// replace tables with split bill header
$('.x-table-container').html('<%= j(render partial: "contracts/elements/split",
  locals: { contract: @contract }) %>');

// replace tables with items table
$('.x-table-container').append('<%= j(render partial: "contracts/elements/items",
  locals: { contract: @contract }) %>');

// append items table with friends table
$('.x-table-container').append('<%= j(render partial: "contracts/elements/friends",
  locals: { contract: @contract }) %>');

// fill friends list
var container = $('.x-transaction-containers');
container.html('<%= j(render partial: "transactions/transaction",
  collection: @transactions, formats: :html) %>');


// fill friends list
var container = $('.x-buttons');
container.html('<%= j(render partial: "contracts/elements/buttons", locals: { contract: @contract }) %>');

<% if @contract.transactions.any? && @contract.transactions.all? { |t| t.status == 'PAID' } %>
$('.x-main-container').html('<%= j(render partial: "contracts/elements/main_container", locals: { contract: @contract }) %>');
<% end %>

web_app/app/views/transactions/update.js.erb
console.log('updated');